version: '3.9'
services:
  trainops:
    build: .
    container_name: trainops_app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run serve
    restart: unless-stopped
